export const GameCommandKind = {
  CreateGame: "CreateGame",
  AddPlayer: "AddPlayer",
  RemovePlayer: "RemovePlayer",
  StartGame: "StartGame",
  AssignRole: "AssignRole",
  DealRoles: "DealRoles",
  BeginNight: "BeginNight",
  ClearFakePlayers: "ClearFakePlayers",
  AdvancePhase: "AdvancePhase",
  MakeNomination: "MakeNomination",
  OpenDay: "OpenDay",
  AddDefense: "AddDefense",
  CastVote: "CastVote",
  SetPlayerVote: "SetPlayerVote",
  KillPlayer: "KillPlayer",
  PauseNominations: "PauseNominations",
  ResumeNominations: "ResumeNominations",
  SetVoteVisibility: "SetVoteVisibility",
  CloseNominations: "CloseNominations",
  ResolveNomination: "ResolveNomination",
  ExecutePlayer: "ExecutePlayer",
  OpenSeats: "OpenSeats",
  CloseSeats: "CloseSeats",
  PickSeat: "PickSeat",
  EndGame: "EndGame",
  PromoteStoryteller: "PromoteStoryteller",
  SetupTown: "SetupTown",
  ResetTownToSetup: "ResetTownToSetup",
  SetPlayerAlive: "SetPlayerAlive",
  SetPlayerDisplayName: "SetPlayerDisplayName",
  LockNominationVotes: "LockNominationVotes",
  UnlockNominationVotes: "UnlockNominationVotes",
  StartNominationCount: "StartNominationCount",
  CountHandVote: "CountHandVote",
  CancelNominationCount: "CancelNominationCount",
} as const;

export type GameCommandKind = (typeof GameCommandKind)[keyof typeof GameCommandKind];
