export const GameEventType = {
  GameCreated: "GameCreated",
  PlayerAdded: "PlayerAdded",
  PlayerRemoved: "PlayerRemoved",
  StorytellerPromoted: "StorytellerPromoted",
  GameStarted: "GameStarted",
  RoleAssigned: "RoleAssigned",
  RolesDealt: "RolesDealt",
  NightStarted: "NightStarted",
  DayStarted: "DayStarted",
  DayOpened: "DayOpened",
  PlayerDied: "PlayerDied",
  NominationMade: "NominationMade",
  DefenseAdded: "DefenseAdded",
  VoteCast: "VoteCast",
  NominationsPaused: "NominationsPaused",
  NominationsResumed: "NominationsResumed",
  VoteVisibilitySet: "VoteVisibilitySet",
  NominationsClosed: "NominationsClosed",
  NominationResolved: "NominationResolved",
  SeatsOpened: "SeatsOpened",
  SeatsClosed: "SeatsClosed",
  SeatPicked: "SeatPicked",
  GameEnded: "GameEnded",
  TownSetup: "TownSetup",
  TownResetToSetup: "TownResetToSetup",
  PlayerAliveChanged: "PlayerAliveChanged",
  PlayerDisplayNameChanged: "PlayerDisplayNameChanged",
  NominationVotesLocked: "NominationVotesLocked",
  NominationVotesUnlocked: "NominationVotesUnlocked",
  NominationCountStarted: "NominationCountStarted",
  NominationCountHandAdvanced: "NominationCountHandAdvanced",
  NominationCountFinished: "NominationCountFinished",
} as const;

export type GameEventType = (typeof GameEventType)[keyof typeof GameEventType];
